name: Deploy to AWS ECS Fargate

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-west-2
  AWS_ACCOUNT_ID: 342051059025
  ECS_CLUSTER_NAME: demo-cluster
  ECS_SERVICE_NAME: demo-service
  IMAGE_NAME: public.ecr.aws/y9k2v6d6/hellodemodocker
  IMAGE_TAG: ${{ github.sha }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Build Docker image
        run: docker build -t ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} .

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Push Docker image to Amazon ECR
        run: |
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/y9k2v6d6
          docker tag ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          docker push ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          
      - name: Create new task definition with updated image
        run: |

          
          task_def_arn=$(aws ecs register-task-definition \
          --family demo-service \
          --requires-compatibilities FARGATE \
          --network-mode awsvpc \
          --cpu 256 \
          --container-definitions "[{\"name\":\"demo-app\",\"image\":\"${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}\",\"essential\":true,\"memory\":512,\"cpu\":256,\"portMappings\":[{\"containerPort\":3000,\"hostPort\":3000,\"protocol\":\"tcp\"}]}]" \
          --query "taskDefinition.taskDefinitionArn" \
          --output text)
          
          echo "$task_def_arn"

      - name: Update Amazon ECS service
        run: |
          aws ecs update-service --cluster ${{ env.ECS_CLUSTER_NAME }} --service ${{ env.ECS_SERVICE_NAME }} --force-new-deployment --task-definition "$task_def_arn"
